In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [ ]:
# TODO 创建一个二维数组
arr = np.array([[1,2],
                [4,5],
                [7,9],
                [11,12]])
print(arr)


In [ ]:
# TODO n维数组的计算
arr = np.array([[2,1,7], 
                [4,2,2]])
print(arr-1)

[[1 0 6]
 [3 1 1]]


In [6]:
# TODO 相同形状数组的计算
arrOne = np.array([[5,0],[0,5]])
arrTwo = np.array([[10,5],[20,5]])
print(arrOne + arrTwo)

[[15  5]
 [20 10]]
