# ndarray
## 1.ndarray特性 # NOTE
### 多维性

In [62]:
import numpy as np

In [67]:
def br():
    print('-' * 60)
def printr(content):
    print(content, '-'*60, sep='\n', end='\n')

In [ ]:
arr = np.array(5) # 创建一个0维ndarray数组
print('内容:', arr)
type(arr)
print('arr的维度:', arr.ndim) # 打印arr的维度

内容 5
arr的维度 0


In [ ]:
arr = np.array([1, 2, 3]) # 创建一个1维ndarray数组
print('内容:', arr)
type(arr)
print('arr的维度:', arr.ndim) # 打印arr的维度

内容: [1 2 3]
arr的维度 1


In [ ]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ]) # 创建一个2维ndarray数组
print('内容:', arr)
type(arr)
print('arr的维度:', arr.ndim) # 打印arr的维度

内容 [[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性 # NOTE

In [18]:
arr = np.array([1, 'hello'])
print(arr)

['1' 'hello']


In [19]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


## 2.ndarray的属性 # NOTE

In [36]:
arr = np.array(1)
print('内容:', arr)
print('arr的形状:', arr.shape)
print('arr的维度:', arr.ndim)
print('arr的元素个数:', arr.size)
print('arr的数据类型:', arr.dtype)
print('arr转置后:', arr.T)


内容: 1
arr的形状: ()
arr的维度: 0
arr的元素个数: 1
arr的数据类型: int32
arr转置后: 1


In [37]:
arr = np.array([1, 2.5, 3])
print('内容:', arr)
print('arr的形状:', arr.shape)
print('arr的维度:', arr.ndim)
print('arr的元素个数:', arr.size)
print('arr的数据类型:', arr.dtype)
print('arr转置后:', arr.T)


内容: [1.  2.5 3. ]
arr的形状: (3,)
arr的维度: 1
arr的元素个数: 3
arr的数据类型: float64
arr转置后: [1.  2.5 3. ]


In [38]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print('内容:', arr)
print('arr的形状:', arr.shape)
print('arr的维度:', arr.ndim)
print('arr的元素个数:', arr.size)
print('arr的数据类型:', arr.dtype)
print('arr转置后:', arr.T)

内容: [[1 2 3]
 [4 5 6]]
arr的形状: (2, 3)
arr的维度: 2
arr的元素个数: 6
arr的数据类型: int32
arr转置后: [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [43]:
# 基础的创建方法
lst1 = [1, 2, 3]
arr = np.array(lst1, dtype=np.float64)
print(arr)

[1. 2. 3.]


In [51]:
# copy
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [70]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2, 3))
print(arr)
br()
arr = np.zeros((2, 3), dtype=int)
print(arr)
br()
arr = np.zeros((200, ))
print(arr)
br()
# 全1
arr = np.ones((5, 8))
print(arr)
br()
# 未初始化
arr = np.empty((4, 3))
printr(arr)
# 固定值
arr = np.full((3, 5), 2025)
printr(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
[[0 0 0]
 [0 0 0]]
------------------------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
---------------------------

In [77]:
# _like模仿形参数组的形状
arr1 = np.zeros_like(arr)
arr2 = np.empty_like(arr)
arr3 = np.ones_like(arr)
arr4 = np.full_like(arr, 2026)
printr(arr1)
printr(arr2)
printr(arr3)
printr(arr4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------------------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------------------------------------
[[2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]]
------------------------------------------------------------


In [81]:
# 等差数列
arr = np.arange(1, 10, 1)
printr(arr)
# 等间隔数列
arr = np.linspace(1, 10, 5)
printr(arr)

[1 2 3 4 5 6 7 8 9]
------------------------------------------------------------
[ 1.    3.25  5.5   7.75 10.  ]
------------------------------------------------------------


In [88]:
# 练习
arr = np.arange(0, 101, 25)
arr2 = np.linspace(0, 100, 5, dtype=int)
print(arr)
print(arr2)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [ ]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2, dtype=int) # base: default = 10
print(arr)

[ 1.  4. 16.]


In [93]:
# 特殊矩阵
# 单位矩阵: 主对角线上的数字为1, 其他的数组为0
arr = np.eye(3, 4, dtype=int)
print(arr)
br()
arr = np.eye(3, dtype=int)
print(arr)
# 对角矩阵: 主对角线上的数字非0, 其余的为0
arr = np.diag([1, 2, 3])
br()
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
------------------------------------------------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------------------------------------------------
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [103]:
# 随机数组的生成
# 生成0到1之间的随机浮点数(均匀分布)
arr = np.random.rand(2, 3)
print(arr)
br()
# 生成指定范围的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)
br()
# 生成指定范围的随机整数
arr = np.random.randint(3, 30, (3, 6))
print(arr)
br()
# 生成随机数列(正太分布: 两边小,中间大) 
arr = np.random.randn(2, 3) # 范围: (-3, 3)
print(arr)

[[0.10450219 0.37261807 0.66241298]
 [0.29976349 0.46616044 0.07319737]]
------------------------------------------------------------
[[4.98203213 4.12268317 5.13343988]
 [3.55021717 3.4824334  4.53337745]]
------------------------------------------------------------
[[ 9 18 14 10  4 20]
 [27 10 17 29 17 28]
 [ 7  5  7  5  7 26]]
------------------------------------------------------------
[[-1.86284015  0.511291   -1.57723895]
 [ 0.43466248 -0.1062695   0.51677043]]


In [106]:
# 设置随机种子: 保证随机生成的数值相同
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


4.ndarray的数据类型 # NOTE

布尔: bool

整形: int uint

浮点型: float

复数: complex

In [109]:
from numpy import uint


arr = np.array([1, 0, 2, 0], dtype='bool') # dtype = 'bool' | bool | np.bool
print(arr)
arr = np.array([1, 0, 255, 0], dtype=uint)
print(arr)

[ True False  True False]
[  1   0 255   0]
