# ndarray
## 1.ndarray特性 # NOTE
### 多维性

In [2]:
import numpy as np

In [3]:
def br():
    print('-' * 60)
def printr(content):
    print(content, '-'*60, sep='\n', end='\n')

In [ ]:
arr = np.array(5) # 创建一个0维ndarray数组
print('内容:', arr)
type(arr)
print('arr的维度:', arr.ndim) # 打印arr的维度

内容 5
arr的维度 0


In [ ]:
arr = np.array([1, 2, 3]) # 创建一个1维ndarray数组
print('内容:', arr)
type(arr)
print('arr的维度:', arr.ndim) # 打印arr的维度

内容: [1 2 3]
arr的维度 1


In [ ]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ]) # 创建一个2维ndarray数组
print('内容:', arr)
type(arr)
print('arr的维度:', arr.ndim) # 打印arr的维度

内容 [[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性 # NOTE

In [18]:
arr = np.array([1, 'hello'])
print(arr)

['1' 'hello']


In [19]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


## 2.ndarray的属性 # NOTE

In [36]:
arr = np.array(1)
print('内容:', arr)
print('arr的形状:', arr.shape)
print('arr的维度:', arr.ndim)
print('arr的元素个数:', arr.size)
print('arr的数据类型:', arr.dtype)
print('arr转置后:', arr.T)


内容: 1
arr的形状: ()
arr的维度: 0
arr的元素个数: 1
arr的数据类型: int32
arr转置后: 1


In [37]:
arr = np.array([1, 2.5, 3])
print('内容:', arr)
print('arr的形状:', arr.shape)
print('arr的维度:', arr.ndim)
print('arr的元素个数:', arr.size)
print('arr的数据类型:', arr.dtype)
print('arr转置后:', arr.T)


内容: [1.  2.5 3. ]
arr的形状: (3,)
arr的维度: 1
arr的元素个数: 3
arr的数据类型: float64
arr转置后: [1.  2.5 3. ]


In [38]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print('内容:', arr)
print('arr的形状:', arr.shape)
print('arr的维度:', arr.ndim)
print('arr的元素个数:', arr.size)
print('arr的数据类型:', arr.dtype)
print('arr转置后:', arr.T)

内容: [[1 2 3]
 [4 5 6]]
arr的形状: (2, 3)
arr的维度: 2
arr的元素个数: 6
arr的数据类型: int32
arr转置后: [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [43]:
# 基础的创建方法
lst1 = [1, 2, 3]
arr = np.array(lst1, dtype=np.float64)
print(arr)

[1. 2. 3.]


In [51]:
# copy
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [70]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2, 3))
print(arr)
br()
arr = np.zeros((2, 3), dtype=int)
print(arr)
br()
arr = np.zeros((200, ))
print(arr)
br()
# 全1
arr = np.ones((5, 8))
print(arr)
br()
# 未初始化
arr = np.empty((4, 3))
printr(arr)
# 固定值
arr = np.full((3, 5), 2025)
printr(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
[[0 0 0]
 [0 0 0]]
------------------------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
---------------------------

In [77]:
# _like模仿形参数组的形状
arr1 = np.zeros_like(arr)
arr2 = np.empty_like(arr)
arr3 = np.ones_like(arr)
arr4 = np.full_like(arr, 2026)
printr(arr1)
printr(arr2)
printr(arr3)
printr(arr4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------------------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------------------------------------
[[2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]
 [2026 2026 2026 2026 2026]]
------------------------------------------------------------


In [81]:
# 等差数列
arr = np.arange(1, 10, 1)
printr(arr)
# 等间隔数列
arr = np.linspace(1, 10, 5)
printr(arr)

[1 2 3 4 5 6 7 8 9]
------------------------------------------------------------
[ 1.    3.25  5.5   7.75 10.  ]
------------------------------------------------------------


In [88]:
# 练习
arr = np.arange(0, 101, 25)
arr2 = np.linspace(0, 100, 5, dtype=int)
print(arr)
print(arr2)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [ ]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2, dtype=int) # base: default = 10
print(arr)

[ 1.  4. 16.]


In [93]:
# 特殊矩阵
# 单位矩阵: 主对角线上的数字为1, 其他的数组为0
arr = np.eye(3, 4, dtype=int)
print(arr)
br()
arr = np.eye(3, dtype=int)
print(arr)
# 对角矩阵: 主对角线上的数字非0, 其余的为0
arr = np.diag([1, 2, 3])
br()
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
------------------------------------------------------------
[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------------------------------------------------
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [103]:
# 随机数组的生成
# 生成0到1之间的随机浮点数(均匀分布)
arr = np.random.rand(2, 3)
print(arr)
br()
# 生成指定范围的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))
print(arr)
br()
# 生成指定范围的随机整数
arr = np.random.randint(3, 30, (3, 6))
print(arr)
br()
# 生成随机数列(正太分布: 两边小,中间大) 
arr = np.random.randn(2, 3) # 范围: (-3, 3)
print(arr)

[[0.10450219 0.37261807 0.66241298]
 [0.29976349 0.46616044 0.07319737]]
------------------------------------------------------------
[[4.98203213 4.12268317 5.13343988]
 [3.55021717 3.4824334  4.53337745]]
------------------------------------------------------------
[[ 9 18 14 10  4 20]
 [27 10 17 29 17 28]
 [ 7  5  7  5  7 26]]
------------------------------------------------------------
[[-1.86284015  0.511291   -1.57723895]
 [ 0.43466248 -0.1062695   0.51677043]]


In [106]:
# 设置随机种子: 保证随机生成的数值相同
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


4.ndarray的数据类型 # NOTE

布尔: bool

整形: int uint

浮点型: float

复数: complex

In [4]:
from numpy import uint


arr = np.array([1, 0, 2, 0], dtype='bool') # dtype = 'bool' | bool | np.bool
print(arr)
arr = np.array([1, 0, 255, 0], dtype=uint)
print(arr)

[ True False  True False]
[  1   0 255   0]


## 5.索引与切片 # NOTE 

In [6]:
# 一维数组
arr = np.random.randint(1, 50, 50)
print(arr)

[ 4 39 45 31 42  3  7 44 47  9 36 25  4 38 11 15 18 24  6 24 13 17 32 31
 28 42 49  1 27 20 29 48 30 45  3 27 32 41 41 22 29 15 20 37 42  8 34 20
 15 46]


In [15]:
print(arr[0])
print(arr[:])
print(arr[2:5])
print(arr[slice(2, 11, 2)])
print(arr[arr>40])
print(arr[ (arr>30) & (arr<40) ])
print(arr[ (arr>40) | (arr<10) ])

4
[ 4 39 45 31 42  3  7 44 47  9 36 25  4 38 11 15 18 24  6 24 13 17 32 31
 28 42 49  1 27 20 29 48 30 45  3 27 32 41 41 22 29 15 20 37 42  8 34 20
 15 46]
[45 31 42]
[45 42  7 47 36]
[45 42 44 47 42 49 48 45 41 41 42 46]
[39 31 36 38 32 31 32 37 34]
[ 4 45 42  3  7 44 47  9  4  6 42 49  1 48 45  3 41 41 42  8 46]


In [19]:
# 二维数组
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[52 10 68 92 88 87 36 34]
 [66 69 50 54 40 46 23 54]
 [54 46 26 44 89 12 38 72]
 [99 27 93 78  4  4 34 44]]


In [29]:
print(arr[2, 3])
print(arr[:,:])
print(arr[1,:])
print(arr[1,2:5])
print(arr[arr>50])
print(arr[2][arr[2]>50])
print(arr[:,3])

44
[[52 10 68 92 88 87 36 34]
 [66 69 50 54 40 46 23 54]
 [54 46 26 44 89 12 38 72]
 [99 27 93 78  4  4 34 44]]
[66 69 50 54 40 46 23 54]
[50 54 40]
[52 68 92 88 87 66 69 54 54 54 89 72 99 93 78]
[54 89 72]
[92 54 44 78]


## 6.ndarray的运算 #NOTE

In [36]:
# 算术运算
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]
[1 4 9]
[1, 2, 3, 4, 5, 6]


In [39]:
# 二维数组
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a + 3)

[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [ 3  3  3]]
[[ 4 10 18]
 [ 4 10 18]]
[[0.25 0.4  0.5 ]
 [4.   2.5  2.  ]]
[[ 1  4  9]
 [16 25 36]]
[[4 5 6]
 [7 8 9]]


In [43]:
# 广播机制
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a)
print(b)
print(a + b)
print(a - b)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]


In [45]:
# 矩阵运算
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 4], [6, 8]])
print(a @ b)

[[14 20]
 [30 44]]


## numpy中的常用函数 # NOTE

### 1.基本数学函数

In [49]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [56]:
# 计算指数, 默认以e为底, e ** x
print(np.exp(1))
print(np.exp(0))

2.718281828459045
1.0


In [61]:
# 计算自然对数 lnX
print(np.log(2.718281828459045))

1.0


In [67]:
# 计算正弦值,余弦值
print(np.sin(30))
print(np.cos(30))
print(np.sin(np.pi/2))

-0.9880316240928618
0.15425144988758405
1.0


In [70]:
# 计算绝对值
arr = np.array([-1, -2, 3 ,5])
print(np.abs(arr))
# 计算幂
print(np.power(arr, 2))

[1 2 3 5]
[ 1  4  9 25]


In [72]:
# 四舍五入
arr = np.array([3.1, 2.8, 4.5, 4.56, 11.3])
print(np.round(arr))

[ 3.  3.  4.  5. 11.]


In [75]:
# 向上取整, 向下取整
print(np.ceil(arr))
print(np.floor(arr))

[ 4.  3.  5.  5. 12.]
[ 3.  2.  4.  4. 11.]


In [81]:
# 检测缺失值 NaN
print(np.isnan([1, 2, 4]))
print(np.isnan([1, 2, np.nan]))


[False False False]
[False False  True]


## 2.统计函数
求和, 平均值, 中位数, 标准差, 方差 \
最大值, 最小值 \
分位数, 累计和, 累计积

In [82]:
arr = np.random.randint(1, 20, 8)
print(arr)

[ 4 14  1 13  2  8 11  2]


In [88]:
# 求和
print(np.sum([1, 2, 3]))
# 平均值
print(np.mean([1, 2, 3]))
# 中位数
print(np.median([1, 2, 4]))
print(np.median([1, 2, 3, 4]))
print(np.median([4, 1, 2]))

6
2.0
2.0
2.5
2.0


In [91]:
# 计算方差
print(np.var([1, 2, 3]))
# 计算标准差
print(np.std([1, 2, 3]))

0.6666666666666666
0.816496580927726


In [95]:
# 计算最大值, 最小值
print(np.max([1, 2, 100, 2, 199, 32]))
print(np.min([1, 2, 100, 2, 199, 32]))
arr = np.array([1, 2, 3, 4])
print(np.percentile(arr, 20))

199
1
1.6


In [98]:
arr = np.array([1, 2, 3])
# 累计和
print(np.cumsum(arr)) # 0+1, 1+2, 3+3
print(np.prod(arr)) # 0*1, 1*2, 2*3

[1 3 6]
6


## 3.比较函数
大于, 小于, 等于 \
与, 或, 非 \
是否有一个True, 是否都为True, 自定义条件

In [123]:
print(np.greater([3, 4, 5, 6, 7], 4)) # 是否大于
print(np.less([3, 4, 5, 6, 7], 4)) # 是否小于
print(np.equal([3, 4, 5, 6, 7], 4)) # 是否等于
print(np.equal([1, 2, 3], [4, 2, 3])) # !形状相同
print(np.logical_and([1, 1], [1, 0])) # 逻辑与
print(np.logical_or([0, 0], [1, 1])) # 逻辑或
print(np.logical_not([1, 0]))  # 逻辑非
print(np.any([1, 0, 0, 1])) # 至少一个为真
print(np.all([1, 0, 0, 1])) # 全部为True
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr>3, arr, 0)) # ?自定义 (条件, 符合, 不符合)
score = np.random.randint(20, 100, 50)
print(np.select([score>80, (score>=60) & (score<=80), score<60], ('优秀', '及格', '不及格'), default='未知')) #?选择 (条件, 返回的结果)



[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True  True]
[ True False]
[ True  True]
[False  True]
True
False
[0 0 0 4 5]
['优秀' '优秀' '不及格' '优秀' '不及格' '及格' '不及格' '及格' '不及格' '不及格' '不及格' '及格' '优秀'
 '及格' '优秀' '不及格' '及格' '不及格' '不及格' '及格' '优秀' '及格' '及格' '及格' '不及格' '及格' '及格'
 '优秀' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '及格' '优秀' '不及格' '不及格' '及格' '优秀'
 '优秀' '及格' '不及格' '不及格' '不及格' '不及格' '及格' '优秀' '及格' '及格']


## 4.排序函数

In [137]:
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
arr.sort() # ?返回None, 从小到大
print(arr)
print(np.sort(arr)) # ?返回一个新数组, 不影响原始数组
print(np.argsort(arr)) # ?返回排序的索引

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [144]:
print(np.unique([1, 3, 1, 2])) # 去重, 并且排序
print(np.concatenate(([1, 2, 3], [4, 5, 6]))) # 拼接数组
print(np.split(arr, 4)) # 分成4份, 不可等分报错
print(np.split(arr, [6, 12, 18])) # 切割的位置
print(np.reshape(arr, [4, 5])) # 重新设置形状 不等分报错

[1 2 3]
[1 2 3 4 5 6]
[array([10, 13, 22, 37, 40]), array([45, 47, 48, 59, 65]), array([66, 68, 68, 71, 84]), array([88, 88, 89, 89, 89])]
[array([10, 13, 22, 37, 40, 45]), array([47, 48, 59, 65, 66, 68]), array([68, 71, 84, 88, 88, 89]), array([89, 89])]
[[10 13 22 37 40]
 [45 47 48 59 65]
 [66 68 68 71 84]
 [88 88 89 89 89]]


In [153]:
# [28, 30, 29, 31, 32, 30, 29]
arr = np.array([28, 30, 29, 31, 32, 30, 29]) # 七天的温度
print('%.2f' % np.mean(arr)) # 平均温度
print(np.max(arr)) # 最高温度
print(np.min(arr)) # 最低温度
print(len(arr[arr>30])) # 温度大于30的天数

29.86
32
28
2


In [156]:
# [85, 90, 78, 92, 88]
scores = np.array([85, 90, 78, 92, 88]) # 成绩
print(np.mean(scores)) # 平均成绩
print(np.median(scores)) # 中位数
print(np.std(scores)) # 标准差
print(scores / 10) # 转换满分为10分

86.6
88.0
4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [158]:
# [[1, 2], [3, 4]], [[5, 6], [7, 8]]
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)
print(A * B)
print(A @ B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [171]:
np.random.seed(20)
integer = np.random.randint(0, 10, (3, 4))
print(integer)
print(np.max(integer, axis=0))
print(np.min(integer, axis=1))
print(np.where(integer%2==1, -1, integer))

[[3 9 4 6]
 [7 2 0 6]
 [8 5 3 0]]
[8 9 4 6]
[3 0 0]
[[-1 -1  4  6]
 [-1  2  0  6]
 [ 8 -1 -1  0]]


In [186]:
arr = np.arange(1, 13)
print(arr)
arr = np.reshape(arr, [3, 4])
print(np.sum(arr, axis=1))
print(np.mean(arr, axis=0))
print(np.reshape(arr, (12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [193]:
np.random.seed(10)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10, 0, arr))

[[ 9  4 15  0 17]
 [16 17  8  9  0]
 [10  8  4 19 16]
 [ 4 15 11 11  1]
 [ 8  4 14 17 19]]
[15 17 16 17 19 16 15 11 11 14 17 19]
[[ 9  4  0  0  0]
 [ 0  0  8  9  0]
 [10  8  4  0  0]
 [ 4  0  0  0  1]
 [ 8  4  0  0  0]]


In [198]:
# [120, 135, 110, 125, 130, 140]
money = np.array([120, 135, 110, 125, 130, 140])
print(np.sum(money))
print(np.mean(money))
print(np.var(money))
print(np.argmax(money) + 1)
print(np.argmin(money) + 1)

760
126.66666666666667
97.22222222222223
6
3


In [204]:
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
print(np.concatenate([a, b]))
c = np.concatenate([a, b])
print(c)
print(np.reshape(c, (2, 3)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [207]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

[1 2 3 4]
[2 2 2 1]


In [3]:
money = np.array([20, 25, 22, 30, 28])
chengben = np.array([15, 18, 16, 22, 20])
omega = money - chengben
print(omega)
print(np.mean(omega))
print(np.std(omega))
print(np.argmax(omega) + 1)

[5 7 6 8 8]
6.8
1.16619037896906
4
